# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20170131_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nearest_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=6)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.Centre')),
            ],
        ),
    ]
