# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0004_auto_20170202_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
