# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_climb_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='creator',
            new_name='owner',
        ),
    ]
